INSERT INTO CATEGORY (CATEGORY_EN_NAME, KO_NAME) VALUES ('leagueoflegends', '롤');
INSERT INTO CATEGORY (CATEGORY_EN_NAME, KO_NAME) VALUES ('fifaonline4', '피파');
INSERT INTO CATEGORY (CATEGORY_EN_NAME, KO_NAME) VALUES ('suddenattack', '서든');
INSERT INTO CATEGORY (CATEGORY_EN_NAME, KO_NAME) VALUES ('battlegrounds', '배그');



INSERT INTO MEMBER VALUES (0, 'admin', '1');
INSERT INTO MEMBER (NICKNAME, PASSWORD) VALUES ('apple', '1');
INSERT INTO MEMBER (NICKNAME, PASSWORD) VALUES ('banana', '1');
INSERT INTO MEMBER (NICKNAME, PASSWORD) VALUES ('coffee', '1');
INSERT INTO MEMBER (NICKNAME, PASSWORD) VALUES ('아이유', '1');